# Generated by Django 2.2 on 2020-03-21 12:59

import cvat.apps.project_submission.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_json', models.FileField(upload_to='submissions/%Y', validators=[django.core.validators.FileExtensionValidator(['json']), cvat.apps.project_submission.validators.validate_json_formatted], verbose_name='Submission JSON')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Submission time')),
                ('mean_average_precision', models.FloatField(default=None, null=True)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_submission', to=settings.AUTH_USER_MODEL, verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Project Submission',
                'verbose_name_plural': 'Project Submissions',
                'ordering': ['-mean_average_precision', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LeaderboardSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_on_leaderboard', models.BooleanField(default=True, verbose_name='Show on leaderboard')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_settings', to=settings.AUTH_USER_MODEL, verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Leaderboard Settings',
                'verbose_name_plural': 'Leaderboard Settings',
            },
        ),
    ]
