# Generated by Django 2.2 on 2020-03-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_submission', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectsubmission',
            options={'ordering': ['-mean_average_precision_leaderboard', 'id'], 'verbose_name': 'Project Submission', 'verbose_name_plural': 'Project Submissions'},
        ),
        migrations.RemoveField(
            model_name='projectsubmission',
            name='mean_average_precision',
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='is_solution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='mean_average_precision_leaderboard',
            field=models.FloatField(default=None, null=True, verbose_name='Leaderboard MAP'),
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='mean_average_precision_total',
            field=models.FloatField(default=None, null=True, verbose_name='Total MAP'),
        ),
        migrations.AlterField(
            model_name='leaderboardsettings',
            name='show_on_leaderboard',
            field=models.BooleanField(default=True, verbose_name='Show this group on the leaderboard'),
        ),
    ]
