# Generated by Django 2.2 on 2020-03-22 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_submission', '0002_auto_20200321_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsubmission',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Group'),
        ),
    ]
