# Generated by Django 3.0.5 on 2020-04-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_submission', '0003_auto_20200322_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsubmission',
            name='is_baseline',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='projectsubmission',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='Submission time'),
        ),
    ]
